// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeeE0__g1kCCI4bOlYQv4mFtXd--7YLJQ',
    appId: '1:397531658760:web:2432f88a7fabc93c2b2fbd',
    messagingSenderId: '397531658760',
    projectId: 'quiz-app-1449e',
    authDomain: 'quiz-app-1449e.firebaseapp.com',
    storageBucket: 'quiz-app-1449e.firebasestorage.app',
    measurementId: 'G-FZ9WES0NL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY4uuWT3zcS_rGLr8ahTMBG1H1WotFrOY',
    appId: '1:397531658760:android:728ae1862f77969d2b2fbd',
    messagingSenderId: '397531658760',
    projectId: 'quiz-app-1449e',
    storageBucket: 'quiz-app-1449e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIijqO2fEMO9nMQWMmTJL0M8Ovq4_Kows',
    appId: '1:397531658760:ios:c1ac677ff98254802b2fbd',
    messagingSenderId: '397531658760',
    projectId: 'quiz-app-1449e',
    storageBucket: 'quiz-app-1449e.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIijqO2fEMO9nMQWMmTJL0M8Ovq4_Kows',
    appId: '1:397531658760:ios:c1ac677ff98254802b2fbd',
    messagingSenderId: '397531658760',
    projectId: 'quiz-app-1449e',
    storageBucket: 'quiz-app-1449e.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeeE0__g1kCCI4bOlYQv4mFtXd--7YLJQ',
    appId: '1:397531658760:web:db4e21c4d668b0862b2fbd',
    messagingSenderId: '397531658760',
    projectId: 'quiz-app-1449e',
    authDomain: 'quiz-app-1449e.firebaseapp.com',
    storageBucket: 'quiz-app-1449e.firebasestorage.app',
    measurementId: 'G-K1214ENEWR',
  );
}
